Repository luyadev/luya-module-admin, pull requests merged in 2018-06, with the labels that each got.

#141 TelephoneLink support for LinkButtonBlock
  CHANGELOG.md
  src/messages/cn/admin.php
  src/messages/de/admin.php
  src/messages/el/admin.php
  src/messages/en/admin.php
  src/messages/es/admin.php
  src/messages/fa/admin.php
  src/messages/fr/admin.php
  src/messages/it/admin.php
  src/messages/pt/admin.php
  src/messages/ru/admin.php
  src/messages/ua/admin.php
  src/messages/vi/admin.php
  src/resources/dist/css/admin.css
  src/resources/dist/js/main.uglified.js
  src/resources/js/directives.js
  src/views/layouts/_angulardirectives.php
Labels: enhancement

#149 Fix MIME type and download counter on file download
  CHANGELOG.md
  src/controllers/FileController.php
Labels: bug

#154 Completion and revision of the French translation
  src/messages/fr/admin.php
Labels: translation
