Repository luyadev/luya-module-admin, pull requests merged in 2020-01, with the labels that each got.

#436 handle click with active state
  CHANGELOG.md
  src/resources/dist/main.css
  src/resources/dist/main.js
  src/resources/js/directives.js
  src/resources/scss/components/_form.scss
Labels: bug

#442 Workaround for check_circle flashing
  CHANGELOG.md
  src/resources/js/login.js
  src/views/login/index.php
Labels: enhancement

#447 migrations #364, #446, #287, #265, #320
  composer.json
  composer.lock
  src/Module.php
  src/apis/UserController.php
  src/base/Controller.php
  src/behaviors/QueueLogBehavior.php
  src/components/AdminUser.php
  src/controllers/DefaultController.php
  src/controllers/LoginController.php
  src/messages/cn/admin.php
  src/messages/de/admin.php
  src/messages/el/admin.php
  src/messages/en/admin.php
  src/messages/es/admin.php
  src/messages/fa/admin.php
  src/messages/fr/admin.php
  src/messages/it/admin.php
  src/messages/nl/admin.php
  src/messages/pl/admin.php
  src/messages/pt/admin.php
  src/messages/ru/admin.php
  src/messages/th/admin.php
  src/messages/tr/admin.php
  src/messages/ua/admin.php
  src/messages/vi/admin.php
  src/migrations/m200128_141129_v3_update.php
  src/models/LoginForm.php
  src/models/QueueLogError.php
  src/models/User.php
  src/models/UserDevice.php
  src/models/UserLogin.php
  src/models/UserLoginLockout.php
  src/resources/dist/login.js
  src/resources/dist/main.css
  src/resources/dist/main.js
  src/resources/js/controllers.js
  src/resources/js/directives.js
  src/resources/js/login.js
  src/resources/js/zaa.js
  src/resources/scss/components/_form.scss
  src/resources/scss/components/_login.scss
  src/views/account/dashboard.php
  src/views/aws/userhistorysummary/index.php
  src/views/login/index.php
  tests/AdminModelTestCase.php
  tests/admin/apis/UserControllerTest.php
  tests/admin/controllers/DefaultControllerTest.php
  tests/admin/controllers/LoginControllerTest.php
  tests/admin/models/QueueLogErrorTest.php
  tests/admin/models/StorageFilterChainTest.php
  tests/admin/models/UserModelTest.php
  tests/assets/.gitignore
Labels: architecture, enhancement
